<?php

use WebId\Flan\Filters\Fields\Checkbox;
use WebId\Flan\Filters\Fields\Date;
use WebId\Flan\Filters\Fields\Number;
use WebId\Flan\Filters\Fields\Select;
use WebId\Flan\Filters\Fields\Text;

return [
    /*
    |--------------------------------------------------------------------------
    | Directory for filter classes
    |--------------------------------------------------------------------------
    |
    | This value is the directory for filter classes generated by artisan
    | commands.
    */

    'filter_class_directory' => app_path('FilterClasses'),

    /*
    |--------------------------------------------------------------------------
    | Directory for filter config
    |--------------------------------------------------------------------------
    |
    | This value is the directory for filter config generated by artisan
    | commands.
    |
    */

    'filter_config_directory' => config_path('FilterConfigs'),

    /*
    |--------------------------------------------------------------------------
    | Default model namespace
    |--------------------------------------------------------------------------
    |
    | This value is the namespace used by artisan commands when generating file
    | from stub. You need to change this if you don't use default laravel model
    | folder.
    |
    */

    'default_model_namespace' => 'App\\Models',

    /*
    |--------------------------------------------------------------------------
    | Default filter class namespace
    |--------------------------------------------------------------------------
    |
    | This value is the namespace used by artisan commands when generating file
    | from stub. Be careful to give it with 'filter_class_directory' config.
    |
    */

    'default_filter_class_namespace' => 'App\\FilterClasses',

    /*
    |--------------------------------------------------------------------------
    | Field classes
    |--------------------------------------------------------------------------
    |
    | This array is for binding type of filter with it field class. You can add
    | custom field here.
    |
    */

    'field_classes' => [
        'text'          => Text::class,
        'number'        => Number::class,
        'checkbox'      => Checkbox::class,
        'select'        => Select::class,
        'date'          => Date::class,
        'datetime'      => Date::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Default date format input
    |--------------------------------------------------------------------------
    |
    | This value is the default format date used by your database like
    | 'created_at'
    |
    */

    'default_date_format_input' => 'Y-m-d H:i:s',

    /*
    |--------------------------------------------------------------------------
    | Default SQL date format output
    |--------------------------------------------------------------------------
    |
    | This value is the default format date return
    |
    */

    'default_sql_date_format_output' => '%Y-%m-%d',

    /*
    |--------------------------------------------------------------------------
    | Default SQL datetime format output
    |--------------------------------------------------------------------------
    |
    | This value is the default format datetime return
    |
    */

    'default_sql_datetime_format_output' => '%Y-%m-%d at %Hh%i',

    /*
    |--------------------------------------------------------------------------
    | Routing
    |--------------------------------------------------------------------------
    |
    | This array is for customize the routing like prefix/name/middlewares. You
    | can also un activate routes.
    |
    */

    'routing' => [
        'filters' => [
            'active' => true,
            'middlewares' => [
                \WebId\Flan\Http\Middleware\IsActive::class,
                \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
                \Illuminate\Session\Middleware\StartSession::class,
                \Illuminate\View\Middleware\ShareErrorsFromSession::class,
                \Illuminate\Routing\Middleware\SubstituteBindings::class,
            ],
            'prefix' => 'filters',
            'name' => 'filters.'
        ],
        'export' => [
            'active' => true,
            'middlewares' => [
                \WebId\Flan\Http\Middleware\IsActive::class,
                \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
                \Illuminate\Session\Middleware\StartSession::class,
                \Illuminate\View\Middleware\ShareErrorsFromSession::class,
                \Illuminate\Routing\Middleware\SubstituteBindings::class,
            ],
            'prefix' => 'filters',
            'name' => 'filters.'
        ]
    ],
];
